### ISSUE TITLE
Restrictive matching makes grouping brittle

### ISSUE THREAD

**Issue by tomash** [tiptone/WNR#1]
Described first [in reddit comment](https://www.reddit.com/r/bourbon/comments/4l70u2/modpost_announcing_whiskynetworkreviewscom/d7uju0j), pasting here:

> This is great! But sometimes it doesn't group the reviews properly, e.g. there are two separate "Aberlour 12 Double Cask Matured" and three "Aberlour A'bunadh batch #49". Probably due very strict matching without removing excessive whitespace characters or unifying case before comparing/grouping. I'd contribute with fixes to these but I have no knowledge of Zend framework.
> 
> yep, it's the lack of whitespace trimming before passing onto search and grouping (trailing space in second query):

```
sqlite> select count(*) from reviews where whiskey like 'Aberlour 12 Double Cask Matured';
41
sqlite> select count(*) from reviews where whiskey like 'Aberlour 12 Double Cask Matured ';
2
```

Suggested fix: remove leading and trailing whitespace, collapse multiple whitespaces into one space, lowercase before searching/comparing/grouping.

**Comment by tiptone** [comment]
I generate the database from a .csv export of a Google Docs spreadsheet, so some data issues are likely to persist. The spreadsheet, and the database, have both been updated this weekend. I tweaked the load script in an effort to address these issues and the majority of reported cases appear to be fixed.
